const PDFDocument = require("pdfkit");

const generateSalaryPDF = (res, data) => {
  const doc = new PDFDocument();

  // Set response headers
  res.setHeader("Content-Type", "application/pdf");
  res.setHeader(
    "Content-Disposition",
    `attachment; filename=salary-slip-${data.name}.pdf`
  );

  doc.pipe(res);

  // 🔹 Title
  doc
    .fontSize(20)
    .text("eSalary System", { align: "center" })
    .moveDown();

  doc
    .fontSize(16)
    .text("Salary Slip", { align: "center" })
    .moveDown(2);

  // 🔹 Faculty Details
  doc.fontSize(12).text(`Name: ${data.name}`);
  doc.text(`Email: ${data.email}`);
  doc.text(`Department: ${data.department}`);
  doc.text(`Designation: ${data.designation}`);
  doc.moveDown();

  // 🔹 Salary Details
  doc.fontSize(14).text("Salary Details", { underline: true });
  doc.moveDown();

  doc.fontSize(12).text(`Basic Salary: ₹${data.basic}`);
  doc.text(`HRA: ₹${data.hra}`);
  doc.text(`Deductions: ₹${data.deductions}`);
  doc.moveDown();

  doc
    .fontSize(14)
    .text(`Net Salary: ₹${data.net_salary}`, {
      underline: true,
    });

  doc.moveDown(2);

  // 🔹 Footer
  doc
    .fontSize(10)
    .text("Generated by eSalary System", { align: "center" });

  doc.end();
};

module.exports = generateSalaryPDF;